<a href="https://colab.research.google.com/github/adamlac23/data-learn/blob/main/01/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np


In [4]:
np.__version__

'1.21.6'

In [6]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [ ]:
help(np.array)

In [8]:
x = np.array([1, 3])
x

array([1, 3])

In [9]:
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
x.ndim

1

In [12]:
x.shape

(2,)

In [13]:
x.size

2

In [14]:
x.dtype

dtype('int64')

In [16]:
x = np.array([1.3, 2.3, 1.4])

In [17]:
print(x)

[1.3 2.3 1.4]


In [18]:
x.dtype

dtype('float64')

In [20]:
x = np.array([[1,2],[-3, 1]])

In [21]:
x.ndim

2

In [22]:
x.shape

(2, 2)

In [23]:
x.type

AttributeError: ignored

In [25]:
x = np.array([[1, 2, 4,], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [26]:
x.shape

(2, 3)

In [28]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]]]

)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [29]:
x.ndim

3

In [30]:
x.shape

(2, 2, 3)

In [31]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [37]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [38]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [39]:
A = np.array([1.1, 2.1, 3.1], dtype='int')
A.dtype

dtype('int64')

In [40]:
A

array([1, 2, 3])

In [41]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [44]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [51]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [54]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [55]:
np.linspace(start=0, stop=1, num=44)

array([0.        , 0.02325581, 0.04651163, 0.06976744, 0.09302326,
       0.11627907, 0.13953488, 0.1627907 , 0.18604651, 0.20930233,
       0.23255814, 0.25581395, 0.27906977, 0.30232558, 0.3255814 ,
       0.34883721, 0.37209302, 0.39534884, 0.41860465, 0.44186047,
       0.46511628, 0.48837209, 0.51162791, 0.53488372, 0.55813953,
       0.58139535, 0.60465116, 0.62790698, 0.65116279, 0.6744186 ,
       0.69767442, 0.72093023, 0.74418605, 0.76744186, 0.79069767,
       0.81395349, 0.8372093 , 0.86046512, 0.88372093, 0.90697674,
       0.93023256, 0.95348837, 0.97674419, 1.        ])

In [56]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
a

NameError: ignored

In [58]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [65]:
A = np.array((3, 1, 4, 2))
B = np.array((3, -1, 3, 2))
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [66]:
A + B

array([6, 0, 7, 4])

In [67]:
A - B


array([0, 2, 1, 0])

In [68]:
A * B

array([ 9, -1, 12,  4])

In [69]:
A / B


array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [71]:
A / B, dtype='int'

SyntaxError: ignored

In [72]:
A + 3

array([6, 4, 7, 5])

In [73]:
A -2

array([ 1, -1,  2,  0])

In [74]:
2 * A

array([6, 2, 8, 4])

In [75]:
abs(A)

array([3, 1, 4, 2])

In [76]:
np.add(A, B)

array([6, 0, 7, 4])

In [77]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [78]:
X * Y

array([[6, 0],
       [2, 0]])

In [79]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [80]:
np.random.seed(0)

In [81]:
np.random.randn()

1.764052345967664

In [82]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [83]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [84]:
np.random.rand()

0.1965823616800535

In [85]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [86]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [87]:
np.random.randint(10)

3

In [91]:
np.random.randint(10)

8

In [92]:
np.random.randint(low=10, high=101)

12

In [93]:
np.random.randint(low=10, high=101, size=10)

array([13, 23, 50, 82, 29, 82, 36, 76, 62, 77])

In [94]:
np.random.choice([4, 2, 1, 4])

4

In [95]:
np.random.choice(['python', 'java'])

'java'

In [96]:
data =np.arange(10)

In [97]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.random.shuffle(data)

In [99]:
data

array([9, 6, 1, 2, 8, 7, 5, 3, 4, 0])

In [100]:
np.exp(1)

2.718281828459045

In [101]:
np.sqrt(9)

3.0

In [102]:
np.all([2, 3,1])

True

In [103]:
np.any([1, 2])

True

In [105]:
bool(1)

True

In [106]:
A = np.random.rand(5)
A

array([0.39650574, 0.8811032 , 0.58127287, 0.88173536, 0.69253159])

In [107]:
np.argmax(A)

3

In [108]:
A[np.argmax(A)]

0.8817353618548528

In [109]:
np.argmin(A)

0

In [110]:
np.argsort(A)

array([0, 2, 4, 1, 3])

In [111]:
np.max(A)

0.8817353618548528

In [112]:
np.min(A)

0.39650574084698464

In [113]:
np.mean(A)

0.6866297525053248

In [115]:
np.median(A)

0.6925315900777659

In [116]:
A = np.arange(20)

In [117]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[ind], A[start:stop], A[:stop], A[start:]

In [118]:
A[2]

2

In [120]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [121]:
A[:2]

array([0, 1])

In [122]:
A[[0, 2]]

array([0, 2])

In [123]:
A[-1]

19

In [124]:
A[10:15]

array([10, 11, 12, 13, 14])

In [126]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [127]:
A[0]

array([0, 1, 2, 3, 4])

In [128]:
A[1]

array([5, 6, 7, 8, 9])

In [130]:
A[:,0]

array([ 0,  5, 10, 15])

In [131]:
A[:,-2]

array([ 3,  8, 13, 18])

In [132]:
A[1,1]

6

In [133]:
A[1, 3]

8

In [135]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [136]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [137]:
for row in A:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [138]:
for row in A:
    print(row[0])

0
5
10
15


In [139]:
for row in A:
    print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [141]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [142]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [143]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [144]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [145]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [146]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [147]:
A = np.arange(start=-10, stop =10, step=0.5)

In [148]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [149]:
A = A.reshape(10, -1)

In [150]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [151]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [152]:
A[A > 0 and ]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [153]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [155]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [156]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])